// build the country list, only name, for example const countriesData = [{value: "Perú", label: "Perú"}, {value: "United State", label: "United State"}] but in spanish


interface SearchProp {
  value: string;
  label: string;
}

export const dataCountry: SearchProp[] = [
  // América del Norte
  { value: "Canada", label: "Canadá" },
  { value: "USA", label: "Estados Unidos" },
  { value: "Mexico", label: "México" },

  // América Central
  // { value: "Belize", label: "Belice" },
  { value: "CostaRica", label: "Costa Rica" },
  { value: "ElSalvador", label: "El Salvador" },
  { value: "Guatemala", label: "Guatemala" },
  { value: "Honduras", label: "Honduras" },
  { value: "Nicaragua", label: "Nicaragua" },
  { value: "Panama", label: "Panamá" },

  // América del Sur
  { value: "Argentina", label: "Argentina" },
  { value: "Bolivia", label: "Bolivia" },
  { value: "Brazil", label: "Brasil" },
  { value: "Chile", label: "Chile" },
  { value: "Colombia", label: "Colombia" },
  { value: "Ecuador", label: "Ecuador" },
  // { value: "Guyana", label: "Guyana" },
  { value: "Paraguay", label: "Paraguay" },
  { value: "Peru", label: "Perú" },
  // { value: "Suriname", label: "Surinam" },
  { value: "Uruguay", label: "Uruguay" },
  { value: "Venezuela", label: "Venezuela" },
];


export const citiesByCountry: { [key: string]: SearchProp[] } = {
  Canada: [
    { value: "Toronto", label: "Toronto" },
    { value: "Vancouver", label: "Vancouver" },
    { value: "Montreal", label: "Montreal" },
    { value: "Calgary", label: "Calgary" },
    { value: "Edmonton", label: "Edmonton" },
    { value: "Ottawa", label: "Ottawa" },
    { value: "Winnipeg", label: "Winnipeg" },
    { value: "QuebecCity", label: "Ciudad de Quebec" },
    { value: "Hamilton", label: "Hamilton" },
    { value: "Halifax", label: "Halifax" },
    { value: "Victoria", label: "Victoria" },
    { value: "London", label: "London" },
    { value: "Kitchener", label: "Kitchener" },
    { value: "StJohns", label: "St. John's" },
    { value: "Regina", label: "Regina" },
    { value: "Saskatoon", label: "Saskatoon" },
    { value: "Kelowna", label: "Kelowna" },
    { value: "Fredericton", label: "Fredericton" },
    { value: "Charlottetown", label: "Charlottetown" },
    { value: "Whitehorse", label: "Whitehorse" },
    { value: "Yellowknife", label: "Yellowknife" },
    { value: "Iqaluit", label: "Iqaluit" },
    // Puedes agregar más ciudades de Canadá según sea necesario
  ],
  USA: [
    { value: "NewYork", label: "Nueva York" },
    { value: "LosAngeles", label: "Los Ángeles" },
    { value: "Chicago", label: "Chicago" },
    { value: "Houston", label: "Houston" },
    { value: "Phoenix", label: "Phoenix" },
    { value: "Philadelphia", label: "Filadelfia" },
    { value: "SanAntonio", label: "San Antonio" },
    { value: "SanDiego", label: "San Diego" },
    { value: "Dallas", label: "Dallas" },
    { value: "SanFrancisco", label: "San Francisco" },
    { value: "Austin", label: "Austin" },
    { value: "Boston", label: "Boston" },
    { value: "Seattle", label: "Seattle" },
    { value: "Denver", label: "Denver" },
    { value: "WashingtonDC", label: "Washington D.C." },
    { value: "Nashville", label: "Nashville" },
    { value: "Atlanta", label: "Atlanta" },
    { value: "Miami", label: "Miami" },
    { value: "Detroit", label: "Detroit" },
    { value: "Minneapolis", label: "Minneapolis" },
    { value: "Tampa", label: "Tampa" },
    { value: "Phoenix", label: "Phoenix" },
    { value: "Portland", label: "Portland" },
    { value: "LasVegas", label: "Las Vegas" },
    // Puedes agregar más ciudades de EE. UU. según sea necesario
  ],
  Mexico: [
    { value: "MexicoCity", label: "Ciudad de México" },
    { value: "Guadalajara", label: "Guadalajara" },
    { value: "Monterrey", label: "Monterrey" },
    { value: "Puebla", label: "Puebla" },
    { value: "Tijuana", label: "Tijuana" },
    { value: "Queretaro", label: "Querétaro" },
    { value: "Merida", label: "Mérida" },
    { value: "Cancun", label: "Cancún" },
    { value: "Acapulco", label: "Acapulco" },
    { value: "Veracruz", label: "Veracruz" },
    { value: "Guaymas", label: "Guaymas" },
    { value: "Oaxaca", label: "Oaxaca" },
    { value: "Culiacan", label: "Culiacán" },
    { value: "Hermosillo", label: "Hermosillo" },
    { value: "Chihuahua", label: "Chihuahua" },
    { value: "Torreon", label: "Torreón" },
    { value: "Morelia", label: "Morelia" },
    { value: "TuxtlaGutierrez", label: "Tuxtla Gutiérrez" },
    { value: "Xalapa", label: "Xalapa" },
    { value: "Toluca", label: "Toluca" },
    { value: "Aguascalientes", label: "Aguascalientes" },
    { value: "Leon", label: "León" },
    { value: "Celaya", label: "Celaya" },
    // Puedes agregar más ciudades de México según sea necesario
  ],
  CostaRica: [
    { value: "SanJose", label: "San José" },
    { value: "Limon", label: "Limón" },
    { value: "Heredia", label: "Heredia" },
    { value: "Alajuela", label: "Alajuela" },
    { value: "Cartago", label: "Cartago" },
    { value: "Puntarenas", label: "Puntarenas" },
    { value: "Guanacaste", label: "Liberia" },
    { value: "PerezZeledon", label: "San Isidro de El General" },
    { value: "Quepos", label: "Quepos" },
    { value: "PuertoLimon", label: "Puerto Limón" },
    { value: "Nicoya", label: "Nicoya" },
    { value: "Upala", label: "Upala" },
    { value: "Liberia", label: "Liberia" },
    { value: "SanRamón", label: "San Ramón" },
    { value: "LaFortuna", label: "La Fortuna" },
    { value: "CiudadQuesada", label: "Ciudad Quesada" },
    { value: "Golfito", label: "Golfito" },
    { value: "SantaCruz", label: "Santa Cruz" },
    { value: "Esparza", label: "Esparza" },
    // Puedes agregar más ciudades de Costa Rica según sea necesario
  ],
  ElSalvador: [
    { value: "SanSalvador", label: "San Salvador" },
    { value: "SantaAna", label: "Santa Ana" },
    { value: "SanMiguel", label: "San Miguel" },
    { value: "Mejicanos", label: "Mejicanos" },
    { value: "Soyapango", label: "Soyapango" },
    { value: "Apopa", label: "Apopa" },
    { value: "Delgado", label: "Delgado" },
    { value: "Sonsonate", label: "Sonsonate" },
    { value: "Usulutan", label: "Usulután" },
    { value: "Cojutepeque", label: "Cojutepeque" },
    { value: "LaUnion", label: "La Unión" },
    { value: "Zacatecoluca", label: "Zacatecoluca" },
    { value: "Ahuachapán", label: "Ahuachapán" },
    { value: "Chalatenango", label: "Chalatenango" },
    { value: "Izalco", label: "Izalco" },
    { value: "LaLibertad", label: "La Libertad" },
    { value: "SanFranciscoGotera", label: "San Francisco Gotera" },
    { value: "Sensuntepeque", label: "Sensuntepeque" },
    // Puedes agregar más ciudades de El Salvador según sea necesario
  ],
  Guatemala: [
    { value: "GuatemalaCity", label: "Ciudad de Guatemala" },
    { value: "Quetzaltenango", label: "Quetzaltenango" },
    { value: "Escuintla", label: "Escuintla" },
    { value: "SanMiguelPetapa", label: "San Miguel Petapa" },
    { value: "Mixco", label: "Mixco" },
    { value: "VillaNueva", label: "Villa Nueva" },
    { value: "Chinautla", label: "Chinautla" },
    { value: "Chimaltenango", label: "Chimaltenango" },
    { value: "Huehuetenango", label: "Huehuetenango" },
    { value: "Quetzaltenango", label: "Quetzaltenango" },
    { value: "SantaCatarinaPinula", label: "Santa Catarina Pinula" },
    { value: "SanJuanSacatepequez", label: "San Juan Sacatepéquez" },
    { value: "Jalapa", label: "Jalapa" },
    { value: "Coatepeque", label: "Coatepeque" },
    { value: "Solola", label: "Sololá" },
    { value: "Chichicastenango", label: "Chichicastenango" },
    { value: "Zacapa", label: "Zacapa" },
    { value: "AntiguaGuatemala", label: "Antigua Guatemala" },
    { value: "Retalhuleu", label: "Retalhuleu" },
    { value: "Coban", label: "Cobán" },
    { value: "PuertoBarrios", label: "Puerto Barrios" },
    // Puedes agregar más ciudades de Guatemala según sea necesario
  ],
  Honduras: [
    { value: "Tegucigalpa", label: "Tegucigalpa" },
    { value: "SanPedroSula", label: "San Pedro Sula" },
    { value: "Choloma", label: "Choloma" },
    { value: "LaCeiba", label: "La Ceiba" },
    { value: "ElProgreso", label: "El Progreso" },
    { value: "Comayagua", label: "Comayagua" },
    { value: "Choluteca", label: "Choluteca" },
    { value: "Danli", label: "Danlí" },
    { value: "Juticalpa", label: "Juticalpa" },
    { value: "Villanueva", label: "Villanueva" },
    { value: "Siguatepeque", label: "Siguatepeque" },
    { value: "Roatan", label: "Roatán" },
    { value: "PuertoCortes", label: "Puerto Cortés" },
    { value: "SantaRosaDeCopan", label: "Santa Rosa de Copán" },
    { value: "LaLima", label: "La Lima" },
    { value: "CopanRuinas", label: "Copán Ruinas" },
    { value: "Yoro", label: "Yoro" },
    { value: "Olancho", label: "Juticalpa, Olancho" },
    { value: "Gracias", label: "Gracias" },
    { value: "Tela", label: "Tela" },
    // Puedes agregar más ciudades de Honduras según sea necesario
  ],
  Nicaragua: [
    { value: "Managua", label: "Managua" },
    { value: "León", label: "León" },
    { value: "Masaya", label: "Masaya" },
    { value: "Granada", label: "Granada" },
    { value: "Matagalpa", label: "Matagalpa" },
    { value: "Chinandega", label: "Chinandega" },
    { value: "Estelí", label: "Estelí" },
    { value: "Juigalpa", label: "Juigalpa" },
    { value: "Bluefields", label: "Bluefields" },
    { value: "Rivas", label: "Rivas" },
    { value: "Jinotepe", label: "Jinotepe" },
    { value: "Somoto", label: "Somoto" },
    { value: "PuertoCabezas", label: "Puerto Cabezas" },
    { value: "Boaco", label: "Boaco" },
    { value: "NuevaGuinea", label: "Nueva Guinea" },
    { value: "Jinotega", label: "Jinotega" },
    { value: "Ocotal", label: "Ocotal" },
    { value: "Jinotepe", label: "Jinotepe" },
    { value: "SanJuanDelSur", label: "San Juan del Sur" },
    { value: "ElViejo", label: "El Viejo" },
    // Puedes agregar más ciudades de Nicaragua según sea necesario
  ],
  Panama: [
    { value: "PanamaCity", label: "Ciudad de Panamá" },
    { value: "SanMiguelito", label: "San Miguelito" },
    { value: "Tocumen", label: "Tocumen" },
    { value: "David", label: "David" },
    { value: "Arraiján", label: "Arraiján" },
    { value: "Colon", label: "Colón" },
    { value: "LasCumbres", label: "Las Cumbres" },
    { value: "LaChorrera", label: "La Chorrera" },
    { value: "Pedregal", label: "Pedregal" },
    { value: "Chitré", label: "Chitré" },
    { value: "Santiago", label: "Santiago" },
    { value: "BocasDelToro", label: "Bocas del Toro" },
    { value: "Penonomé", label: "Penonomé" },
    { value: "LaVillaDeLosSantos", label: "La Villa de Los Santos" },
    { value: "Aguadulce", label: "Aguadulce" },
    { value: "Volcán", label: "Volcán" },
    { value: "Chepo", label: "Chepo" },
    { value: "Antón", label: "Antón" },
    { value: "LaPintada", label: "La Pintada" },
    { value: "ElEmpalme", label: "El Empalme" },
    // Puedes agregar más ciudades de Panamá según sea necesario
  ],
  Argentina: [
    { value: "BuenosAires", label: "Buenos Aires" },
    { value: "Cordoba", label: "Córdoba" },
    { value: "Rosario", label: "Rosario" },
    { value: "Mendoza", label: "Mendoza" },
    { value: "LaPlata", label: "La Plata" },
    { value: "SanMigueldeTucuman", label: "San Miguel de Tucumán" },
    { value: "MarDelPlata", label: "Mar del Plata" },
    { value: "Salta", label: "Salta" },
    { value: "SantaFe", label: "Santa Fe" },
    { value: "SanJuan", label: "San Juan" },
    { value: "Resistencia", label: "Resistencia" },
    { value: "Neuquen", label: "Neuquén" },
    { value: "Corrientes", label: "Corrientes" },
    { value: "Posadas", label: "Posadas" },
    { value: "BahiaBlanca", label: "Bahía Blanca" },
    { value: "RioGallegos", label: "Río Gallegos" },
    { value: "Formosa", label: "Formosa" },
    { value: "Parana", label: "Paraná" },
    { value: "SanLuis", label: "San Luis" },
    { value: "Ushuaia", label: "Ushuaia" },
    // Puedes agregar más ciudades de Argentina según sea necesario
  ],
  Bolivia: [
    { value: "LaPaz", label: "La Paz" },
    { value: "SantaCruz", label: "Santa Cruz" },
    { value: "Cochabamba", label: "Cochabamba" },
    { value: "Sucre", label: "Sucre" },
    { value: "Tarija", label: "Tarija" },
    { value: "Potosi", label: "Potosí" },
    { value: "Oruro", label: "Oruro" },
    { value: "Trinidad", label: "Trinidad" },
    { value: "Cobija", label: "Cobija" },
    { value: "Riberalta", label: "Riberalta" },
    { value: "Guayaramerin", label: "Guayaramerín" },
    { value: "Camiri", label: "Camiri" },
    { value: "Bermejo", label: "Bermejo" },
    { value: "Villazon", label: "Villazón" },
    { value: "Sacaba", label: "Sacaba" },
    { value: "Quillacollo", label: "Quillacollo" },
    { value: "Huanuni", label: "Huanuni" },
    { value: "Cotoca", label: "Cotoca" },
    { value: "Montero", label: "Montero" },
    { value: "Warnes", label: "Warnes" },
    // Puedes agregar más ciudades de Bolivia según sea necesario
  ],
  Brazil: [
    { value: "RioDeJaneiro", label: "Río de Janeiro" },
    { value: "SaoPaulo", label: "São Paulo" },
    { value: "Brasilia", label: "Brasilia" },
    { value: "Salvador", label: "Salvador" },
    { value: "Fortaleza", label: "Fortaleza" },
    { value: "BeloHorizonte", label: "Belo Horizonte" },
    { value: "Manaus", label: "Manaus" },
    { value: "Curitiba", label: "Curitiba" },
    { value: "Recife", label: "Recife" },
    { value: "PortoAlegre", label: "Porto Alegre" },
    { value: "Goiânia", label: "Goiânia" },
    { value: "Belem", label: "Belém" },
    { value: "SaoLuis", label: "São Luís" },
    { value: "Campinas", label: "Campinas" },
    { value: "SaoGoncalo", label: "São Gonçalo" },
    { value: "Maceio", label: "Maceió" },
    { value: "DuqueDeCaxias", label: "Duque de Caxias" },
    { value: "Joinville", label: "Joinville" },
    { value: "FeiraDeSantana", label: "Feira de Santana" },
    { value: "Natal", label: "Natal" },
    // Puedes agregar más ciudades de Brasil según sea necesario
  ],
  Chile: [
    { value: "Santiago", label: "Santiago" },
    { value: "Valparaiso", label: "Valparaíso" },
    { value: "Concepcion", label: "Concepción" },
    { value: "Antofagasta", label: "Antofagasta" },
    { value: "VinaDelMar", label: "Viña del Mar" },
    { value: "Temuco", label: "Temuco" },
    { value: "Valdivia", label: "Valdivia" },
    { value: "LaSerena", label: "La Serena" },
    { value: "Iquique", label: "Iquique" },
    { value: "PuertoMontt", label: "Puerto Montt" },
    { value: "Rancagua", label: "Rancagua" },
    { value: "Talca", label: "Talca" },
    { value: "Arica", label: "Arica" },
    { value: "Chillan", label: "Chillán" },
    { value: "Osorno", label: "Osorno" },
    { value: "Quillota", label: "Quillota" },
    { value: "PuntaArenas", label: "Punta Arenas" },
    { value: "Calama", label: "Calama" },
    { value: "Copiapo", label: "Copiapó" },
    { value: "Coquimbo", label: "Coquimbo" },
    // Puedes agregar más ciudades de Chile según sea necesario
  ],
  Colombia: [
    { value: "Bogota", label: "Bogotá" },
    { value: "Medellin", label: "Medellín" },
    { value: "Cali", label: "Cali" },
    { value: "Barranquilla", label: "Barranquilla" },
    { value: "Cartagena", label: "Cartagena" },
    { value: "Cucuta", label: "Cúcuta" },
    { value: "Bucaramanga", label: "Bucaramanga" },
    { value: "Pereira", label: "Pereira" },
    { value: "SantaMarta", label: "Santa Marta" },
    { value: "Ibague", label: "Ibagué" },
    { value: "Pasto", label: "Pasto" },
    { value: "Manizales", label: "Manizales" },
    { value: "Neiva", label: "Neiva" },
    { value: "Villavicencio", label: "Villavicencio" },
    { value: "Armenia", label: "Armenia" },
    { value: "Monteria", label: "Montería" },
    { value: "Popayan", label: "Popayán" },
    { value: "Valledupar", label: "Valledupar" },
    { value: "Buenaventura", label: "Buenaventura" },
    { value: "Sincelejo", label: "Sincelejo" },
    // Puedes agregar más ciudades de Colombia según sea necesario
  ],
  Ecuador: [
    { value: "Quito", label: "Quito" },
    { value: "Guayaquil", label: "Guayaquil" },
    { value: "Cuenca", label: "Cuenca" },
    { value: "Ambato", label: "Ambato" },
    { value: "Machala", label: "Machala" },
    { value: "Portoviejo", label: "Portoviejo" },
    { value: "Ibarra", label: "Ibarra" },
    { value: "Loja", label: "Loja" },
    { value: "Riobamba", label: "Riobamba" },
    { value: "SantoDomingo", label: "Santo Domingo" },
    { value: "Manta", label: "Manta" },
    { value: "Quevedo", label: "Quevedo" },
    { value: "Milagro", label: "Milagro" },
    { value: "Esmeraldas", label: "Esmeraldas" },
    { value: "Tulcan", label: "Tulcán" },
    { value: "SantaRosa", label: "Santa Rosa" },
    { value: "Latacunga", label: "Latacunga" },
    { value: "Azogues", label: "Azogues" },
    { value: "Macas", label: "Macas" },
    {
      value: "PuertoFranciscoDeOrellana",
      label: "Puerto Francisco de Orellana (El Coca)",
    },
    // Puedes agregar más ciudades de Ecuador según sea necesario
  ],
  Paraguay: [
    { value: "Asuncion", label: "Asunción" },
    { value: "CiudadDelEste", label: "Ciudad del Este" },
    { value: "SanLorenzo", label: "San Lorenzo" },
    { value: "Capiata", label: "Capiatá" },
    { value: "Lambare", label: "Lambaré" },
    { value: "FernandoDeLaMora", label: "Fernando de la Mora" },
    { value: "Luque", label: "Luque" },
    { value: "Limpio", label: "Limpio" },
    { value: "Encarnacion", label: "Encarnación" },
    {
      value: "ColoniaMariscalEstigarribia",
      label: "Colonia Mariscal Estigarribia",
    },
    { value: "Ita", label: "Itá" },
    { value: "VillaElisa", label: "Villa Elisa" },
    { value: "PedroJuanCaballero", label: "Pedro Juan Caballero" },
    { value: "CoronelOviedo", label: "Coronel Oviedo" },
    { value: "Villarrica", label: "Villarrica" },
    { value: "Caacupe", label: "Caacupé" },
    { value: "Pilar", label: "Pilar" },
    { value: "Caaguazu", label: "Caaguazú" },
    { value: "SanJuanBautista", label: "San Juan Bautista" },
    { value: "Ypacarai", label: "Ypacaraí" },

    // Puedes agregar más ciudades de Paraguay según sea necesario
  ],
  Peru: [
    { value: "Lima", label: "Lima" },
    { value: "Arequipa", label: "Arequipa" },
    { value: "Trujillo", label: "Trujillo" },
    { value: "Chiclayo", label: "Chiclayo" },
    { value: "Piura", label: "Piura" },
    { value: "Cusco", label: "Cusco" },
    { value: "Iquitos", label: "Iquitos" },
    { value: "Huancayo", label: "Huancayo" },
    { value: "Chimbote", label: "Chimbote" },
    { value: "Tacna", label: "Tacna" },
    { value: "Ica", label: "Ica" },
    { value: "Pucallpa", label: "Pucallpa" },
    { value: "Juliaca", label: "Juliaca" },
    { value: "Sullana", label: "Sullana" },
    { value: "Ayacucho", label: "Ayacucho" },
    { value: "ChinchaAlta", label: "Chincha Alta" },
    { value: "Huaraz", label: "Huaraz" },
    { value: "Tarapoto", label: "Tarapoto" },
    { value: "Huacho", label: "Huacho" },
    { value: "Puno", label: "Puno" },
    // Puedes agregar más ciudades de Perú según sea necesario
  ],
  Uruguay: [
    { value: "Montevideo", label: "Montevideo" },
    { value: "Salto", label: "Salto" },
    { value: "Paysandu", label: "Paysandú" },
    { value: "LasPiedras", label: "Las Piedras" },
    { value: "Rivera", label: "Rivera" },
    { value: "Maldonado", label: "Maldonado" },
    { value: "Tacuarembo", label: "Tacuarembó" },
    { value: "Melow", label: "Melo" },
    { value: "Mercedes", label: "Mercedes" },
    { value: "Artigas", label: "Artigas" },
    { value: "Minas", label: "Minas" },
    { value: "SanJoseDeMayo", label: "San José de Mayo" },
    { value: "Durazno", label: "Durazno" },
    { value: "Florida", label: "Florida" },
    { value: "TreintaYTres", label: "Treinta y Tres" },
    { value: "Rocha", label: "Rocha" },
    { value: "SanCarlos", label: "San Carlos" },
    { value: "Pando", label: "Pando" },
    { value: "FrayBentos", label: "Fray Bentos" },
    { value: "ColoniaDelSacramento", label: "Colonia del Sacramento" },
    // Puedes agregar más ciudades de Uruguay según sea necesario
  ],
  Venezuela: [
    { value: "Caracas", label: "Caracas" },
    { value: "Maracaibo", label: "Maracaibo" },
    { value: "Valencia", label: "Valencia" },
    { value: "Barquisimeto", label: "Barquisimeto" },
    { value: "Maracay", label: "Maracay" },
    { value: "CiudadGuayana", label: "Ciudad Guayana" },
    { value: "SanCristobal", label: "San Cristóbal" },
    { value: "Barcelona", label: "Barcelona" },
    { value: "Maturin", label: "Maturín" },
    { value: "Cabimas", label: "Cabimas" },
    { value: "PuertoLaCruz", label: "Puerto La Cruz" },
    { value: "Guarenas", label: "Guarenas" },
    { value: "Merida", label: "Mérida" },
    { value: "Barinas", label: "Barinas" },
    { value: "CiudadBolivar", label: "Ciudad Bolívar" },
    { value: "Cumana", label: "Cumaná" },
    { value: "SanFelix", label: "San Félix" },
    { value: "LosTeques", label: "Los Teques" },
    { value: "Guacara", label: "Guacara" },
    { value: "PuntoFijo", label: "Punto Fijo" },
    // Puedes agregar más ciudades de Venezuela según sea necesario
  ],
};